In [ ]:
import pandas as pd
import joblib

df = pd.read_csv("../../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
X = df.drop("Churn", axis=1)

In [26]:
X.shape

(7043, 7076)

In [41]:
import joblib

lr = joblib.load("../models/best_model.pkl")

In [51]:
lr

LogisticRegression(max_iter=1000)

In [60]:
print("Number of Features:", len(X.columns))
print("Number of Coefficients:", len(lr.coef_[0]))

Number of Features: 7076
Number of Coefficients: 13601

In [68]:
print("X shape:", X.shape)
print("Model shape:", lr.coef_.shape)

for i, col in enumerate(X.columns):
    print(i, col)

X shape: (7043, 7076)
Model shape: (1, 13601)
0 SeniorCitizen
1 tenure
2 MonthlyCharges
3 TotalCharges
4 AvgRevenue
5 customerID_0003-MKNFE
6 customerID_0004-TLHLJ
7 customerID_0011-IGKFF
8 customerID_0013-EXCHZ
9 customerID_0013-MHZWF
10 customerID_0013-SMEOE
11 customerID_0014-BMAQU
12 customerID_0015-UOCOJ
13 customerID_0016-QLJIS
14 customerID_0017-DINOC
15 customerID_0017-IUDMW
16 customerID_0018-NYROU
17 customerID_0019-EFAEP
18 customerID_0019-GFNTW
19 customerID_0020-INWCK
20 customerID_0020-JDNXP
21 customerID_0021-IKXGC
22 customerID_0022-TCJCI
23 customerID_0023-HGHWL
24 customerID_0023-UYUPN
25 customerID_0023-XUOPT
26 customerID_0027-KWYKW
27 customerID_0030-FNXPP
28 customerID_0031-PVLZI
29 customerID_0032-PGELS
30 customerID_0036-IHMOT
31 customerID_0040-HALCW
32 customerID_0042-JVWOJ
33 customerID_0042-RLHYP
34 customerID_0048-LUMLS
35 customerID_0048-PIHNL
36 customerID_0052-DCKON
37 customerID_0052-YNYOT
38 customerID_0056-EPFBG
39 customerID_0057-QBUQH
40 customerID_0058-EVZWM
41 customerID_0060-FUALY
42 customerID_0064-SUDOG
43 customerID_0064-YIJGF
44 customerID_0067-DKWBL
45 customerID_0068-FIGTF
46 customerID_0071-NDAFP
47 customerID_0074-HDKDG
48 customerID_0076-LVEPS
49 customerID_0078-XZMHT
50 customerID_0080-EMYVY
51 customerID_0080-OROZO
52 customerID_0082-LDZUE
53 customerID_0082-OQIQY
54 customerID_0083-PIVIK
55 customerID_0089-IIQKO
56 customerID_0093-EXYQL
57 customerID_0093-XWZFY
58 customerID_0094-OIFMO
59 customerID_0096-BXERS
60 customerID_0096-FCPUF
61 customerID_0098-BOWSO
62 customerID_0100-DUVFC
63 customerID_0103-CSITQ
64 customerID_0104-PPXDV
65 customerID_0106-GHRQR
66 customerID_0106-UGRDO
67 customerID_0107-WESLM
68 customerID_0107-YHINA
69 customerID_0111-KLBQG
70 customerID_0112-QAWRZ
71 customerID_0112-QWPNC
72 customerID_0114-IGABW
73 customerID_0114-PEGZZ
74 customerID_0114-RSRRW
75 customerID_0115-TFERT
76 customerID_0117-LFRMW
77 customerID_0118-JPNOY
78 customerID_0121-SNYRK
79 customerID_0122-OAHPZ
80 customerID_0123-CRBRT
81 customerID_0125-LZQXK
82 customerID_0128-MKWSG
83 customerID_0129-KPTWJ
84 customerID_0129-QMPDR
85 customerID_0130-SXOUN
86 customerID_0133-BMFZO
87 customerID_0134-XWXCE
88 customerID_0135-NMXAP
89 customerID_0136-IFMYD
90 customerID_0137-OCGAB
91 customerID_0137-UDEUO
92 customerID_0139-IVFJG
93 customerID_0141-YEAYS
94 customerID_0142-GVYSN
95 customerID_0147-ESWWR
96 customerID_0148-DCDOS
97 customerID_0151-ONTOV
98 customerID_0156-FVPTA
99 customerID_0164-APGRB
100 customerID_0164-XAIRP
101 customerID_0168-XZKBB
102 customerID_0174-QRVVY
103 customerID_0177-PXBAT
104 customerID_0178-CIIKR
105 customerID_0178-SZBHO
106 customerID_0181-RITDD
107 customerID_0186-CAERR
108 customerID_0187-QSXOE
109 customerID_0187-WZNAB
110 customerID_0188-GWFLE
111 customerID_0191-EQUUH
112 customerID_0191-ZHSKZ
113 customerID_0193-ESZXP
114 customerID_0195-IESCP
115 customerID_0196-JTUQI
116 customerID_0196-VULGZ
117 customerID_0197-PNKNK
118 customerID_0201-MIBOL
119 customerID_0201-OAMXR
120 customerID_0203-HHYIJ
121 customerID_0206-OYVOC
122 customerID_0206-TBWLC
123 customerID_0207-MDKNV
124 customerID_0208-BPQEJ
125 customerID_0212-ISBBF
126 customerID_0214-JHPFW
127 customerID_0215-BQKGS
128 customerID_0218-QNVAS
129 customerID_0219-QAERP
130 customerID_0219-YTZUE
131 customerID_0220-EBGCE
132 customerID_0221-NAUXK
133 customerID_0221-WMXNQ
134 customerID_0222-CNVPT
135 customerID_0224-HJAPT
136 customerID_0224-NIJLP
137 customerID_0224-RLWWD
138 customerID_0225-ZORZP
139 customerID_0228-MAUWC
140 customerID_0229-LFJAF
141 customerID_0230-UBYPQ
142 customerID_0230-WEQUW
143 customerID_0231-LXVAP
144 customerID_0233-FTHAV
145 customerID_0234-TEVTT
146 customerID_0235-KGSLC
147 customerID_0236-HFWSV
148 customerID_0237-YFUTL
149 customerID_0238-WHBIQ
150 customerID_0239-OXEXL
151 customerID_0244-LGNFY
152 customerID_0247-SLUJI
153 customerID_0248-IPDFW
154 customerID_0248-PGHBZ
155 customerID_0253-ZTEOB
156 customerID_0254-FNMCI
157 customerID_0254-KCJGT
158 customerID_0254-WWRKD
159 customerID_0256-LTHVJ
160 customerID_0257-KXZGU
161 customerID_0257-ZESQC
162 customerID_0258-NOKBL
163 customerID_0259-GBZSH
164 customerID_0260-ZDLGK
165 customerID_0263-FJTQO
166 customerID_0264-CNITK
167 customerID_0265-EDXBD
168 customerID_0265-PSUAE
169 customerID_0266-CLZKZ
170 customerID_0266-GMEAO
171 customerID_0268-QKIWO
172 customerID_0269-XFESX
173 customerID_0270-THENM
174 customerID_0274-JKUJR
175 customerID_0277-BKSQP
176 customerID_0277-ORXQS
177 customerID_0278-YXOOG
178 customerID_0280-XJGEX
179 customerID_0281-CNTZX
180 customerID_0282-NVSJS
181 customerID_0285-INHLN
182 customerID_0289-IVARM
183 customerID_0292-WEGCH
184 customerID_0295-PPHDO
185 customerID_0295-QVKPB
186 customerID_0297-RBCSG
187 customerID_0298-XACET
188 customerID_0301-FIDRB
189 customerID_0301-KOBTQ
190 customerID_0302-JOIVN
191 customerID_0303-UNCIP
192 customerID_0303-WMMRN
193 customerID_0305-SQECB
194 customerID_0306-JAELE
195 customerID_0307-BCOPK
196 customerID_0308-GIQJT
197 customerID_0308-IVGOK
198 customerID_0310-MVLET
199 customerID_0310-SUCIN
200 customerID_0310-VQXAM
201 customerID_0311-QYWSS
202 customerID_0311-UNPFF
203 customerID_0314-TKOSI
204 customerID_0315-LVCRK
205 customerID_0318-QUUOB
206 customerID_0318-ZOPWS
207 customerID_0319-QZTCO
208 customerID_0320-DWVTU
209 customerID_0320-JDNQG
210 customerID_0322-CHQRU
211 customerID_0322-YINQP
212 customerID_0323-XWWTN
213 customerID_0324-BRPCJ
214 customerID_0325-XBFAC
215 customerID_0326-VDYXE
216 customerID_0327-WFZSY
217 customerID_0328-GRPMV
218 customerID_0329-GTIAJ
219 customerID_0330-BGYZE
220 customerID_0330-IVZHA
221 customerID_0334-GDDSO
222 customerID_0334-ZFJSR
223 customerID_0336-KXKFK
224 customerID_0336-PIKEI
225 customerID_0337-CNPZE
226 customerID_0343-QLUZP
227 customerID_0345-HKJVM
228 customerID_0345-XMMUG
229 customerID_0347-UBKUZ
230 customerID_0348-SDKOL
231 customerID_0354-VXMJC
232 customerID_0354-WYROK
233 customerID_0356-ERHVT
234 customerID_0356-OBMAC
235 customerID_0357-NVCRI
236 customerID_0361-HJRDX
237 customerID_0362-RAOQO
238 customerID_0362-ZBZWJ
239 customerID_0363-QJVFX
240 customerID_0363-SVHYR
241 customerID_0365-BZUWY
242 customerID_0365-GXEZS
243 customerID_0365-TRTPY
244 customerID_0366-NQSHS
245 customerID_0369-ZGOVK
246 customerID_0373-AIVNJ
247 customerID_0374-AACSZ
248 customerID_0374-FIUCA
249 customerID_0374-IOEGQ
250 customerID_0375-HVGXO
251 customerID_0376-OIWME
252 customerID_0376-YMCJC
253 customerID_0377-JBKKT
254 customerID_0378-CJKPV
255 customerID_0378-NHQXU
256 customerID_0378-TOVMS
257 customerID_0378-XSZPU
258 customerID_0379-DJQHR
259 customerID_0380-NEAVX
260 customerID_0380-ZCSBI
261 customerID_0383-CLDDA
262 customerID_0384-LPITE
263 customerID_0384-RVBPI
264 customerID_0386-CWRGM
265 customerID_0388-EOPEX
266 customerID_0390-DCFDQ
267 customerID_0392-BZIUW
268 customerID_0394-YONDK
269 customerID_0396-HUJBP
270 customerID_0396-UKGAI
271 customerID_0396-YCHWO
272 customerID_0397-GZBBC
273 customerID_0397-ZXWQF
274 customerID_0401-WDBXM
275 customerID_0402-CQAJN
276 customerID_0402-OAMEN
277 customerID_0404-AHASP
278 customerID_0404-SWRVG
279 customerID_0406-BPDVR
280 customerID_0407-BDJKB
281 customerID_0409-WTMPL
282 customerID_0410-IPFTY
283 customerID_0411-EZJZE
284 customerID_0412-UCCNP
285 customerID_0415-MOSGF
286 customerID_0419-YAAPX
287 customerID_0420-BWTPW
288 customerID_0420-HLGXF
289 customerID_0420-TXVSG
290 customerID_0422-OHQHQ
291 customerID_0422-UXFAP
292 customerID_0423-UDIJQ
293 customerID_0426-TIRNE
294 customerID_0428-AXXLJ
295 customerID_0428-IKYCP
296 customerID_0430-IHCDJ
297 customerID_0431-APWVY
298 customerID_0432-CAJZV
299 customerID_0434-CSFON
300 customerID_0436-TWFFZ
301 customerID_0439-IFYUN
302 customerID_0440-EKDCF
303 customerID_0440-MOGPM
304 customerID_0440-QEXBZ
305 customerID_0440-UEDAI
306 customerID_0442-TDYUO
307 customerID_0442-ZXKVS
308 customerID_0447-BEMNG
309 customerID_0447-RXSGD
310 customerID_0454-OKRCT
311 customerID_0455-ENTCR
312 customerID_0455-XFASS
313 customerID_0458-HEUZG
314 customerID_0459-SPZHJ
315 customerID_0461-CVKMU
316 customerID_0463-TXOAK
317 customerID_0463-WZZKO
318 customerID_0463-ZSDNT
319 customerID_0464-WJTKO
320 customerID_0468-YRPXN
321 customerID_0471-ARVMX
322 customerID_0471-LVHGK
323 customerID_0475-RIJEP
324 customerID_0479-HMSWA
325 customerID_0480-BIXDE
326 customerID_0480-KYJVA
327 customerID_0481-SUMCB
328 customerID_0484-FFVBJ
329 customerID_0484-JPBRU
330 customerID_0485-ZBSLN
331 customerID_0486-HECZI
332 customerID_0486-LGCCH
333 customerID_0487-CRLZF
334 customerID_0487-RPVUM
335 customerID_0487-VVUVK
336 customerID_0488-GSLFR
337 customerID_0489-WMEMG
338 customerID_0491-KAPQG
339 customerID_0495-RVCBF
340 customerID_0495-ZBNGW
341 customerID_0496-AHOOK
342 customerID_0504-HHAPI
343 customerID_0505-SPOOW
344 customerID_0506-LVNGN
345 customerID_0506-YLVKJ
346 customerID_0508-OOLTO
347 customerID_0508-SQWPL
348 customerID_0511-JTEOY
349 customerID_0512-FLFDW
350 customerID_0513-RBGPE
351 customerID_0515-YPMCW
352 customerID_0516-OOHAR
353 customerID_0516-QREYC
354 customerID_0516-UXRMT
355 customerID_0516-VRYBW
356 customerID_0516-WJVXC
357 customerID_0519-DRGTI
358 customerID_0519-XUZJU
359 customerID_0520-FDVVT
360 customerID_0523-VNGTF
361 customerID_0524-IAVZO
362 customerID_0526-SXDJP
363 customerID_0529-ONKER
364 customerID_0530-IJVDB
365 customerID_0531-XBKMM
366 customerID_0531-ZZJWQ
367 customerID_0533-BNWKF
368 customerID_0533-UCAAU
369 customerID_0536-ACXIP
370 customerID_0536-BGFMZ
371 customerID_0536-ESJEP
372 customerID_0537-QYZZN
373 customerID_0541-FITGH
374 customerID_0547-HURJB
375 customerID_0549-CYCQN
376 customerID_0550-DCXLH
377 customerID_0556-FJEGU
378 customerID_0557-ASKVU
379 customerID_0559-CKHUS
380 customerID_0562-FGDCR
381 customerID_0562-HKHML
382 customerID_0562-KBDVM
383 customerID_0564-JJHGS
384 customerID_0564-MUUQK
385 customerID_0565-IYCGT
386 customerID_0565-JUPYD
387 customerID_0567-GGCAC
388 customerID_0567-XRHCU
389 customerID_0568-ONFPC
390 customerID_0570-BFQHT
391 customerID_0572-ZJKLT
392 customerID_0575-CUQOV
393 customerID_0576-WNXXC
394 customerID_0577-WHMEV
395 customerID_0578-SKVMF
396 customerID_0580-PIQHM
397 customerID_0581-BXBUB
398 customerID_0581-MDMPW
399 customerID_0582-AVCLN
400 customerID_0584-BJQGZ
401 customerID_0585-EGDDA
402 customerID_0587-DMGBH
403 customerID_0594-UFTUL
404 customerID_0595-ITUDF
405 customerID_0596-BQCEQ
406 customerID_0599-XNYDO
407 customerID_0601-WZHJF
408 customerID_0602-DDUML
409 customerID_0603-OLQDC
410 customerID_0603-TPMIB
411 customerID_0604-THJFP
412 customerID_0607-DAAHE
413 customerID_0607-MVMGC
414 customerID_0608-JDVEC
415 customerID_0611-DFXKO
416 customerID_0612-RTZZA
417 customerID_0613-WUXUM
418 customerID_0616-ATFGB
419 customerID_0617-AQNWT
420 customerID_0617-FHSGK
421 customerID_0618-XWMSS
422 customerID_0619-OLYUR
423 customerID_0620-DLSLK
424 customerID_0620-XEFWH
425 customerID_0621-CXBKL
426 customerID_0621-HJWXJ
427 customerID_0621-JFHOL
428 customerID_0621-TSSMU
429 customerID_0621-TWIEM
430 customerID_0623-EJQEG
431 customerID_0623-GDISB
432 customerID_0623-IIHUG
433 customerID_0625-AFOHS
434 customerID_0626-QXNGV
435 customerID_0628-CNQRM
436 customerID_0634-SZPQA
437 customerID_0635-WKOLD
438 customerID_0637-KVDLV
439 customerID_0637-UBJRP
440 customerID_0637-YLETY
441 customerID_0639-TSIQW
442 customerID_0640-YJTPY
443 customerID_0641-EVBOJ
444 customerID_0643-OKLRP
445 customerID_0644-OQMDK
446 customerID_0650-BWOZN
447 customerID_0654-HMSHN
448 customerID_0654-PQKDW
449 customerID_0655-RBDUG
450 customerID_0655-YDGFJ
451 customerID_0657-DOGUM
452 customerID_0661-KBKPA
453 customerID_0661-KQHNK
454 customerID_0661-WCQNQ
455 customerID_0661-XEYAN
456 customerID_0665-XHDJU
457 customerID_0666-UXTJO
458 customerID_0667-NSRGI
459 customerID_0668-OGMHD
460 customerID_0670-ANMUU
461 customerID_0670-KDOMA
462 customerID_0673-IGUQO
463 customerID_0674-DGMAQ
464 customerID_0674-EYYZV
465 customerID_0674-GCDXG
466 customerID_0675-NCDYU
467 customerID_0678-RLHVP
468 customerID_0679-IDSTG
469 customerID_0679-TDGAK
470 customerID_0680-DFNNY
471 customerID_0682-USIXD
472 customerID_0684-AOSIH
473 customerID_0685-MLYYM
474 customerID_0687-ZVTHB
475 customerID_0689-DSXGL
476 customerID_0689-NKYLF
477 customerID_0690-SRQID
478 customerID_0691-IFBQW
479 customerID_0691-JVSYA
480 customerID_0691-NIKRI
481 customerID_0696-UKTOX
482 customerID_0697-ZMSWS
483 customerID_0699-NDKJM
484 customerID_0701-RFGFI
485 customerID_0701-TJSEF
486 customerID_0702-PGIBZ
487 customerID_0704-VCUMB
488 customerID_0707-HOVVN
489 customerID_0708-LGSMF
490 customerID_0708-SJDIS
491 customerID_0709-TVGUR
492 customerID_0716-BQNDX
493 customerID_0719-SYFRB
494 customerID_0722-SVSFK
495 customerID_0722-TROQR
496 customerID_0723-DRCLG
497 customerID_0723-FDLAY
498 customerID_0723-VSOBE
499 customerID_0725-CXOTM
500 customerID_0727-BMPLR
501 customerID_0727-BNRLG
502 customerID_0727-IWKVK
503 customerID_0730-BGQGF
504 customerID_0730-KOAVE
505 customerID_0731-EBJQB
506 customerID_0732-OCQOC
507 customerID_0733-VUNUW
508 customerID_0734-OXWBT
509 customerID_0739-UUAJR
510 customerID_0742-LAFQK
511 customerID_0742-MOABM
512 customerID_0742-NXBGR
513 customerID_0743-HNPFG
514 customerID_0743-HRVFF
515 customerID_0744-BIKKF
516 customerID_0744-GKNGE
517 customerID_0746-JTRFU
518 customerID_0748-RDGGM
519 customerID_0749-IRGQE
520 customerID_0750-EBAIU
521 customerID_0750-EKNGL
522 customerID_0754-EEBDC
523 customerID_0754-UKWQP
524 customerID_0756-MPZRL
525 customerID_0757-WCUUZ
526 customerID_0761-AETCS
527 customerID_0769-MURVM
528 customerID_0771-CHWSK
529 customerID_0771-WLCLA
530 customerID_0772-GYEQQ
531 customerID_0774-IFUVM
532 customerID_0774-RMNUW
533 customerID_0778-NELLA
534 customerID_0780-XNZFN
535 customerID_0781-LKXBR
536 customerID_0784-GTUUK
537 customerID_0784-ZQJZX
538 customerID_0786-IVLAW
539 customerID_0786-VSSUD
540 customerID_0787-LHDYT
541 customerID_0788-DXBFY
542 customerID_0793-TWELN
543 customerID_0794-YVSGE
544 customerID_0795-GMVQO
545 customerID_0795-LAFGP
546 customerID_0795-XCCTE
547 customerID_0799-DDIHE
548 customerID_0804-XBFBV
549 customerID_0804-YGEQV
550 customerID_0807-ZABDG
551 customerID_0810-BDHAW
552 customerID_0810-DHDBD
553 customerID_0811-GSDTP
554 customerID_0812-WUPTB
555 customerID_0813-TAXXS
556 customerID_0815-MFZGM
557 customerID_0816-TSPHQ
558 customerID_0817-HSUSE
559 customerID_0818-OCPZO
560 customerID_0820-FNRNX
561 customerID_0822-GAVAP
562 customerID_0822-QGCXA
563 customerID_0823-HSCDJ
564 customerID_0824-VWDPO
565 customerID_0825-CPPQH
566 customerID_0827-ITJPH
567 customerID_0829-DDVLK
568 customerID_0829-XXPLX
569 customerID_0831-JNISG
570 customerID_0835-DUUIQ
571 customerID_0835-JKADZ
572 customerID_0836-SEYLU
573 customerID_0839-JTCUD
574 customerID_0839-QNXME
575 customerID_0840-DCNZE
576 customerID_0840-DFEZH
577 customerID_0841-NULXI
578 customerID_0842-IWYCP
579 customerID_0843-WTBXE
580 customerID_0847-HGRML
581 customerID_0848-SOMKO
582 customerID_0848-ZGQIJ
583 customerID_0851-DFJKB
584 customerID_0853-NWIFK
585 customerID_0853-TWRVK
586 customerID_0854-UYHZD
587 customerID_0856-NAOES
588 customerID_0859-YGKFW
589 customerID_0862-PRCBS
590 customerID_0864-FVJNJ
591 customerID_0866-QLSIR
592 customerID_0867-LDTTC
593 customerID_0867-MKZVY
594 customerID_0868-VJRDR
595 customerID_0869-PAPRP
596 customerID_0870-VEMYL
597 customerID_0871-OPBXW
598 customerID_0871-URUWO
599 customerID_0872-CASZJ
600 customerID_0872-JCPIB
601 customerID_0872-NXJYS
602 customerID_0875-CABNR
603 customerID_0876-WDUUZ
604 customerID_0877-SDMBN
605 customerID_0880-FVFWF
606 customerID_0880-TKATG
607 customerID_0883-EIBTI
608 customerID_0885-HMGPY
609 customerID_0886-QGENL
610 customerID_0887-HJGAR
611 customerID_0887-WBJVH
612 customerID_0895-DQHEW
613 customerID_0895-LMRSF
614 customerID_0895-LNKRC
615 customerID_0895-UADGO
616 customerID_0897-FEGMU
617 customerID_0898-XCGTF
618 customerID_0899-LIIBW
619 customerID_0899-WZRSD
620 customerID_0902-RFHOF
621 customerID_0902-XKXPN
622 customerID_0906-QVPMS
623 customerID_0907-HQNTS
624 customerID_0909-SDHNU
625 customerID_0909-SELIE
626 customerID_0913-XWSCN
627 customerID_0916-KNFAJ
628 customerID_0916-QOFDP
629 customerID_0917-EZOLA
630 customerID_0921-OHLVP
631 customerID_0923-PNFUB
632 customerID_0924-BJCRC
633 customerID_0925-VYDLG
634 customerID_0927-CNGRH
635 customerID_0927-LCSMG
636 customerID_0928-JMXNP
637 customerID_0928-XUTSN
638 customerID_0929-HYQEW
639 customerID_0929-PECLO
640 customerID_0930-EHUZA
641 customerID_0931-MHTEM
642 customerID_0932-YIXYU
643 customerID_0936-NQLJU
644 customerID_0939-EREMR
645 customerID_0939-YAPAF
646 customerID_0940-OUQEC
647 customerID_0942-KOWSM
648 customerID_0943-ZQPXH
649 customerID_0945-TSONX
650 customerID_0946-CLJTI
651 customerID_0946-FKYTX
652 customerID_0947-IDHRQ
653 customerID_0947-MUGVO
654 customerID_0952-KMEEH
655 customerID_0953-LGOVU
656 customerID_0956-ACVZC
657 customerID_0956-SYCWG
658 customerID_0958-YHXGP
659 customerID_0959-WHOKV
660 customerID_0960-HUWBM
661 customerID_0961-ZWLVI
662 customerID_0962-CQPWQ
663 customerID_0963-ZBDRN
664 customerID_0967-BMLBD
665 customerID_0968-GSIKN
666 customerID_0969-RGKCU
667 customerID_0970-ETWGE
668 customerID_0970-QXPXW
669 customerID_0971-QIFJK
670 customerID_0973-KYVNF
671 customerID_0975-UYDTX
672 customerID_0975-VOOVL
673 customerID_0979-MOZQI
674 customerID_0979-PHULV
675 customerID_0980-FEXWF
676 customerID_0980-PVMRC
677 customerID_0983-TATYJ
678 customerID_0988-AADSA
679 customerID_0988-JRWWP
680 customerID_0991-BRRFB
681 customerID_0993-OSGPT
682 customerID_0997-YTLNY
683 customerID_0999-QXNSA
684 customerID_1000-AJSLD
685 customerID_1004-NOZNR
686 customerID_1009-IRMNA
687 customerID_1010-DIAUQ
688 customerID_1013-QCWAM
689 customerID_1015-JPFYW
690 customerID_1015-OWJKI
691 customerID_1016-DJTSV
692 customerID_1017-FBQMM
693 customerID_1020-JPQOW
694 customerID_1022-RKXDR
695 customerID_1023-BQXZE
696 customerID_1024-GUALD
697 customerID_1024-KPRBB
698 customerID_1024-VRZHF
699 customerID_1025-FALIX
700 customerID_1027-LKKQQ
701 customerID_1028-FFNJK
702 customerID_1029-QFBEN
703 customerID_1031-IIDEO
704 customerID_1032-MAELW
705 customerID_1035-IPQPU
706 customerID_1036-GUDCL
707 customerID_1038-RQOST
708 customerID_1038-ZAGBI
709 customerID_1041-RXHRA
710 customerID_1042-HFUCW
711 customerID_1043-UXOVO
712 customerID_1043-YCUTE
713 customerID_1045-LTCYT
714 customerID_1047-NNCBF
715 customerID_1047-RNXZV
716 customerID_1049-FYSYG
717 customerID_1051-EQPZR
718 customerID_1051-GEJLJ
719 customerID_1052-QJIBV
720 customerID_1053-MXTTK
721 customerID_1057-FOGLZ
722 customerID_1060-ENTOF
723 customerID_1061-PNTHC
724 customerID_1062-LHZOD
725 customerID_1063-DHQJF
726 customerID_1064-FBXNK
727 customerID_1066-JKSGK
728 customerID_1069-QJOEE
729 customerID_1069-XAIEM
730 customerID_1073-XXCZD
731 customerID_1074-AMIOH
732 customerID_1074-WVEVG
733 customerID_1075-BGWOH
734 customerID_1077-HUUJM
735 customerID_1078-TDCRN
736 customerID_1080-BWSYE
737 customerID_1084-MNSMJ
738 customerID_1084-UQCHV
739 customerID_1085-LDWAM
740 customerID_1086-LXKFY
741 customerID_1087-GRUYI
742 customerID_1087-UDSIH
743 customerID_1088-AUUZZ
744 customerID_1088-CNNKB
745 customerID_1089-HDMKP
746 customerID_1089-XZWHH
747 customerID_1090-ESELR
748 customerID_1090-PYKCI
749 customerID_1091-SOZGA
750 customerID_1092-GANHU
751 customerID_1092-WPIVQ
752 customerID_1093-YSWCA
753 customerID_1094-BKOSX
754 customerID_1095-JUDTC
755 customerID_1095-WGNGG
756 customerID_1096-ADRUX
757 customerID_1097-FSPVW
758 customerID_1098-KFQEC
759 customerID_1098-TDVUQ
760 customerID_1099-BTKWT
761 customerID_1099-GODLO
762 customerID_1100-DDVRV
763 customerID_1101-SSWAG
764 customerID_1104-FEJAM
765 customerID_1104-TNLZA
766 customerID_1106-HRLKZ
767 customerID_1110-KYLGQ
768 customerID_1112-CUNAO
769 customerID_1113-IUJYX
770 customerID_1114-CENIM
771 customerID_1116-DXXDF
772 customerID_1116-FRYVH

In [75]:
len(X.columns)

7076

In [81]:
X_temp = X.drop(
    columns=[
        "AvgRevenue",
        "TenureGroup_1-2 Years",
        "TenureGroup_2-4 Years",
        "TenureGroup_4-6 Years"
    ]
)

print(X_temp.shape)

(7043, 7072)

In [127]:
coefs = lr.coef_.ravel()

model_feature_names = getattr(lr, "feature_names_in_", None)
features = list(model_feature_names) if model_feature_names is not None else list(X_temp.columns)

if len(features) != len(coefs):
    min_len = min(len(features), len(coefs))
    features = features[:min_len]
    coefs = coefs[:min_len]

importance = pd.DataFrame({"Feature": features, "Coefficient": coefs})
importance = importance.sort_values(by="Coefficient", ascending=False)
importance.head(15)

                                    Feature  Coefficient
7051                      MultipleLines_Yes     0.424310
7069  PaymentMethod_Credit card (automatic)     0.410758
3506                  customerID_4958-XCBDQ     0.272739
7067                      Contract_Two year     0.260533
2                            MonthlyCharges     0.177768
0                             SeniorCitizen     0.174141
203                   customerID_0315-LVCRK     0.174093
4862                  customerID_6849-OYAMU     0.160522
700                   customerID_1028-FFNJK     0.153876
5348                  customerID_7551-DACSP     0.147931
1992                  customerID_2876-GZYZC     0.146872
4359                  customerID_6140-QNRQQ     0.142582
5919                  customerID_8329-GWVPJ     0.142548
3440                  customerID_4873-ILOLJ     0.139143
932                   customerID_1347-KTTTA     0.137884